"""Numbering lanes — pinned blocks (#333) and the golden-equivalence guarantee.

Two families of tests:

1. **Golden equivalence.** With zero pinned blocks, ``reassign_all_channels`` and
   ``get_next_channel_number`` must produce *exactly* the numbers the pre-#333
   allocator produced. The expected maps below were generated by running the
   pre-#333 code (``teamarr/database/channel_numbers.py`` at dev ``0129cda1``)
   against the same fixture — do not "fix" them to match new output.

2. **Lane behaviour.** Team / league / sport pins, precedence, groups, spill,
   bounded overflow, stability modes inside lanes, relayout arming, and the v88
   migration from manual mode.
"""

import json
import sqlite3

import pytest

from teamarr.database import channel_numbers as cn
from teamarr.database import numbering_exceptions as ne

# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------

SCHEMA = """
CREATE TABLE settings (
  id INTEGER PRIMARY KEY, channel_range_start INTEGER DEFAULT 101, channel_range_end INTEGER,
  global_channel_mode TEXT DEFAULT 'auto', league_channel_starts TEXT DEFAULT '{}',
  global_consolidation_mode TEXT DEFAULT 'consolidate',
  channel_stability_mode TEXT DEFAULT 'compact',
  channel_gap_size INTEGER DEFAULT 1, channel_daily_reset_enabled INTEGER DEFAULT 1,
  channel_daily_reset_time TEXT DEFAULT '04:00', last_channel_reset_at TEXT,
  force_channel_relayout_pending INTEGER DEFAULT 0, schema_version INTEGER DEFAULT 87);
CREATE TABLE event_epg_groups (id INTEGER PRIMARY KEY, enabled INTEGER DEFAULT 1);
CREATE TABLE managed_channels (
  id INTEGER PRIMARY KEY, dispatcharr_channel_id INTEGER, channel_number TEXT,
  channel_number_locked INTEGER DEFAULT 0, channel_name TEXT, event_epg_group_id INTEGER,
  primary_stream_id INTEGER, event_id TEXT, sport TEXT, league TEXT,
  home_team TEXT, away_team TEXT, event_date TEXT, exception_keyword TEXT,
  created_at TEXT, deleted_at TEXT);
CREATE TABLE channel_sort_priorities (
  id INTEGER PRIMARY KEY, sport TEXT, league_code TEXT, sort_priority INTEGER,
  created_at TEXT, updated_at TEXT);
CREATE TABLE channel_priority_teams (id INTEGER PRIMARY KEY, sport TEXT, team_name TEXT);
CREATE TABLE leagues (league_code TEXT PRIMARY KEY, sport TEXT, display_name TEXT);
CREATE TABLE team_cache (
  id INTEGER PRIMARY KEY, provider TEXT, provider_team_id TEXT, team_name TEXT,
  sport TEXT, league TEXT);
CREATE TABLE numbering_exceptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    scope TEXT NOT NULL CHECK(scope IN ('team', 'league', 'sport')),
    sport TEXT NOT NULL, league_code TEXT, team_name TEXT, provider TEXT, provider_team_id TEXT,
    start INTEGER NOT NULL, "end" INTEGER, label TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0, enabled BOOLEAN DEFAULT 1);
INSERT INTO settings (id) VALUES (1);
INSERT INTO leagues VALUES ('nfl','football','NFL'),('nba','basketball','NBA'),
  ('nhl','hockey','NHL'),('mlb','baseball','MLB'),('ncaaf','football','NCAA Football'),
  ('fifa.world','soccer','FIFA World Cup');
INSERT INTO team_cache (provider, provider_team_id, team_name, sport, league) VALUES
  ('espn','8','Detroit Lions','football','nfl'),
  ('espn','9','Green Bay Packers','football','nfl'),
  ('espn','20','Detroit Pistons','basketball','nba'),
  ('espn','17','Detroit Red Wings','hockey','nhl'),
  ('espn','6','Detroit Tigers','baseball','mlb');
"""

# id, name, number, locked, date, event_id, sport, league, home, away, keyword
CHANNELS = [
    (1, "Lions @ Packers", None, 0, "2026-09-13 17:00:00", "nfl1", "football", "nfl",
     "Green Bay Packers", "Detroit Lions", None),
    (2, "Lions @ Packers [HOME]", None, 0, "2026-09-13 17:00:00", "nfl1", "football", "nfl",
     "Green Bay Packers", "Detroit Lions", None),
    (3, "Bears @ Vikings", None, 0, "2026-09-13 20:00:00", "nfl2", "football", "nfl",
     "Minnesota Vikings", "Chicago Bears", None),
    (4, "Bears @ Vikings ES", None, 0, "2026-09-13 20:00:00", "nfl2", "football", "nfl",
     "Minnesota Vikings", "Chicago Bears", "spanish"),
    (5, "Pistons @ Bulls", None, 0, "2026-09-13 19:00:00", "nba1", "basketball", "nba",
     "Chicago Bulls", "Detroit Pistons", None),
    (6, "Celtics @ Heat", None, 0, "2026-09-14 19:00:00", "nba2", "basketball", "nba",
     "Miami Heat", "Boston Celtics", None),
    (7, "Red Wings @ Leafs", None, 0, "2026-09-13 19:00:00", "nhl1", "hockey", "nhl",
     "Toronto Maple Leafs", "Detroit Red Wings", None),
    (8, "Tigers @ Yankees", None, 0, "2026-09-13 13:00:00", "mlb1", "baseball", "mlb",
     "New York Yankees", "Detroit Tigers", None),
    (9, "Tigers @ Yankees G2", None, 0, "2026-09-13 18:00:00", "mlb2", "baseball", "mlb",
     "New York Yankees", "Detroit Tigers", None),
    (10, "Michigan @ Ohio State", None, 0, "2026-09-12 12:00:00", "cfb1", "football", "ncaaf",
     "Ohio State Buckeyes", "Michigan Wolverines", None),
    (11, "World Cup: USA v MEX", None, 0, "2026-09-15 15:00:00", "wc1", "soccer", "fifa.world",
     "USA", "Mexico", None),
]
PRIORITIES = [
    ("football", None, 0), ("basketball", None, 1), ("hockey", None, 2),
    ("football", "nfl", 0), ("football", "ncaaf", 1),
]


def build(mode="auto", stab="compact", gap=1, starts=None, range_start=101, range_end=None,
          locked=None):
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    c.execute(
        "UPDATE settings SET global_channel_mode=?, channel_stability_mode=?, channel_gap_size=?, "
        "league_channel_starts=?, channel_range_start=?, channel_range_end=?",
        (mode, stab, gap, json.dumps(starts or {}), range_start, range_end),
    )
    for s, lg, p in PRIORITIES:
        c.execute(
            "INSERT INTO channel_sort_priorities (sport, league_code, sort_priority)"
            " VALUES (?,?,?)",
            (s, lg, p),
        )
    locked = locked or {}
    for row in CHANNELS:
        cid, name, num, lk, date, eid, sport, league, home, away, kw = row
        if cid in locked:
            num, lk = locked[cid], 1
        c.execute(
            "INSERT INTO managed_channels (id, channel_name, channel_number, channel_number_locked,"
            " event_date, event_id, sport, league, home_team, away_team, exception_keyword)"
            " VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (cid, name, num, lk, date, eid, sport, league, home, away, kw),
        )
    return c


def numbers(c) -> dict[int, int]:
    return {
        r["id"]: int(r["channel_number"])
        for r in c.execute("SELECT id, channel_number FROM managed_channels ORDER BY id")
        if r["channel_number"] is not None
    }


def pin(c, scope, start, **kw):
    exc = ne.add_numbering_exception(c, scope=scope, start=start, **kw)
    assert exc is not None, f"pin failed: {scope} {start} {kw}"
    return exc


# ---------------------------------------------------------------------------
# 1. Golden equivalence (pre-#333 outputs; zero pinned blocks)
# ---------------------------------------------------------------------------

GOLDEN = {
    "auto_compact": {1: 101, 2: 102, 3: 103, 4: 104, 5: 106, 6: 107, 7: 108, 8: 109, 9: 110,
                     10: 105, 11: 111},
    "auto_compact_ext": {1: 500, 2: 503, 3: 504, 4: 505, 5: 508, 6: 509, 7: 510, 8: 511,
                         9: 512, 10: 506, 11: 513},
    "gap_first_placement": {1: 101, 2: 102, 3: 105, 4: 106, 5: 112, 6: 115, 7: 118, 8: 121,
                            9: 124, 10: 109, 11: 127},
    "gap_sticky_anchors": {1: 101, 2: 102, 3: 105, 4: 106, 5: 120, 6: 123, 7: 126, 8: 129,
                           9: 132, 10: 109, 11: 135},
    "gap_reset": {1: 101, 2: 102, 3: 105, 4: 106, 5: 112, 6: 115, 7: 118, 8: 121, 9: 124,
                  10: 109, 11: 127},
    "strict_sticky_anchors": {1: 101, 2: 102, 3: 104, 4: 105, 5: 103, 6: 107, 7: 108, 8: 109,
                              9: 110, 10: 106, 11: 111},
    "strict_reset": {1: 101, 2: 102, 3: 103, 4: 104, 5: 106, 6: 107, 7: 108, 8: 109, 9: 110,
                     10: 105, 11: 111},
}


def test_golden_auto_compact():
    c = build()
    cn.reassign_all_channels(c)
    assert numbers(c) == GOLDEN["auto_compact"]


def test_golden_auto_compact_external_occupied():
    c = build(range_start=500)
    cn.reassign_all_channels(c, external_occupied={501, 502, 507})
    assert numbers(c) == GOLDEN["auto_compact_ext"]


def test_golden_gap_first_placement():
    c = build(stab="gap", gap=3)
    cn.reassign_all_channels(c)
    assert numbers(c) == GOLDEN["gap_first_placement"]


def test_golden_gap_sticky_with_anchors():
    c = build(stab="gap", gap=3, locked={1: 101, 2: 102, 3: 105, 4: 106, 5: 120})
    cn.reassign_all_channels(c)
    assert numbers(c) == GOLDEN["gap_sticky_anchors"]


def test_golden_gap_reset():
    c = build(stab="gap", gap=3, locked={1: 140, 2: 141, 5: 101, 7: 110})
    cn.reassign_all_channels(c, force_reset=True)
    assert numbers(c) == GOLDEN["gap_reset"]


def test_golden_strict_sticky_with_anchors():
    c = build(stab="strict", locked={1: 101, 2: 102, 5: 103})
    cn.reassign_all_channels(c)
    assert numbers(c) == GOLDEN["strict_sticky_anchors"]


def test_golden_strict_reset():
    c = build(stab="strict", locked={1: 140, 2: 141, 5: 101})
    cn.reassign_all_channels(c, force_reset=True)
    assert numbers(c) == GOLDEN["strict_reset"]


def test_golden_next_channel_auto():
    c = build()
    cn.reassign_all_channels(c)
    assert cn.get_next_channel_number(c) == 112


# ---------------------------------------------------------------------------
# 2. v88 migration: manual mode → league pinned blocks
# ---------------------------------------------------------------------------

# Pre-#333 `_reassign_manual` output for starts {nfl:500, nba:600, nhl:700}, range 101:
# listed leagues sequential from their start; EVERY unlisted league restarted at
# 101 independently (ids 8, 10, 11 all = 101 — a collision). Lanes keep the listed
# numbers exactly and fix the collision.
MANUAL_LISTED = {1: 500, 2: 501, 3: 502, 4: 503, 5: 600, 6: 601, 7: 700}


def _migrate(c):
    from teamarr.database.migrations.versioned import _migrate_v88_numbering_exceptions

    _migrate_v88_numbering_exceptions(c)


def test_v88_manual_listed_leagues_identical_and_unlisted_fixed():
    c = build(mode="manual", starts={"nfl": 500, "nba": 600, "nhl": 700}, range_start=101)
    _migrate(c)
    settings = c.execute(
        "SELECT global_channel_mode, channel_stability_mode FROM settings"
    ).fetchone()
    assert settings["global_channel_mode"] == "auto"
    assert settings["channel_stability_mode"] == "compact"
    rows = ne.get_numbering_exceptions(c)
    assert [(r.scope, r.league_code, r.start, r.sport) for r in rows] == [
        ("league", "nfl", 500, "football"),
        ("league", "nba", 600, "basketball"),
        ("league", "nhl", 700, "hockey"),
    ]

    cn.reassign_all_channels(c)
    got = numbers(c)
    assert {k: got[k] for k in MANUAL_LISTED} == MANUAL_LISTED
    # Unlisted leagues share the default lane in sort order (ncaaf before mlb x2, wc last).
    assert (got[10], got[8], got[9], got[11]) == (101, 102, 103, 104)


def test_v88_manual_with_external_occupied_matches_listed():
    # Pre-#333: {1:501, 2:502, 3:503, 4:504, 5:600, 6:602} with ext {500, 601}
    c = build(mode="manual", starts={"nfl": 500, "nba": 600}, range_start=101)
    _migrate(c)
    cn.reassign_all_channels(c, external_occupied={500, 601})
    got = numbers(c)
    expected = {1: 501, 2: 502, 3: 503, 4: 504, 5: 600, 6: 602}
    assert {k: got[k] for k in expected} == expected


def test_v88_next_channel_for_pinned_league_matches_manual():
    # Pre-#333: next for nfl after reassign = 504; unlisted league = 103
    c = build(mode="manual", starts={"nfl": 500})
    _migrate(c)
    cn.reassign_all_channels(c)
    assert cn.get_next_channel_number(c, league="nfl", sport="football") == 504
    # unlisted leagues now share the default lane: 7 channels there → 101..107, next 108
    assert cn.get_next_channel_number(c, league="mlb", sport="baseball") == 108


def test_v88_auto_mode_untouched():
    c = build(mode="auto", stab="gap", gap=3, starts={"nfl": 500})
    _migrate(c)
    settings = c.execute("SELECT channel_stability_mode FROM settings").fetchone()
    assert settings["channel_stability_mode"] == "gap"
    assert ne.get_numbering_exceptions(c) == []


def test_v88_is_idempotent():
    c = build(mode="manual", starts={"nfl": 500})
    _migrate(c)
    c.execute("UPDATE settings SET global_channel_mode = 'manual'")
    _migrate(c)
    assert len(ne.get_numbering_exceptions(c)) == 1


# ---------------------------------------------------------------------------
# 3. Lane behaviour
# ---------------------------------------------------------------------------


def test_team_pin_covers_both_sides_and_feeds():
    c = build()
    pin(c, "team", 800, provider="espn", provider_team_id="8")  # Lions (away in nfl1)
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert (got[1], got[2]) == (800, 801)  # both feeds of the Lions game, contiguous
    # everything else compact from 101 in sort order, Lions game removed
    assert got[3] == 101 and got[10] == 103 and got[5] == 104


def test_detroit_example_layout():
    """The motivating layout from #333: four team pins + a big-events group + default."""
    c = build(range_start=8000)
    pin(c, "team", 800, provider="espn", provider_team_id="8")   # Lions
    pin(c, "team", 810, provider="espn", provider_team_id="20")  # Pistons
    pin(c, "team", 820, provider="espn", provider_team_id="17")  # Red Wings
    pin(c, "team", 830, provider="espn", provider_team_id="6")   # Tigers
    pin(c, "league", 850, league_code="fifa.world", label="Big events")
    pin(c, "league", 1700, league_code="nfl")
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert (got[1], got[2]) == (800, 801)
    assert got[5] == 810
    assert got[7] == 820
    assert (got[8], got[9]) == (830, 831)
    assert got[11] == 850
    assert (got[3], got[4]) == (1700, 1701)  # NFL game without a pinned team
    assert (got[10], got[6]) == (8000, 8001)  # ncaaf, then nba (sort order)


def test_precedence_home_team_beats_away_team():
    c = build()
    pin(c, "team", 800, provider="espn", provider_team_id="8")  # Lions (away)
    pin(c, "team", 900, provider="espn", provider_team_id="9")  # Packers (home)
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert (got[1], got[2]) == (900, 901)


def test_precedence_team_beats_league_beats_sport():
    c = build()
    pin(c, "sport", 300, sport="football")
    pin(c, "league", 500, league_code="nfl")
    pin(c, "team", 800, provider="espn", provider_team_id="8")
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert got[1] == 800          # Lions game → team pin
    assert got[3] == 500          # other NFL game → league pin
    assert got[10] == 300         # ncaaf → sport pin


def test_group_rows_share_one_lane():
    c = build()
    pin(c, "league", 850, league_code="fifa.world", label="Big events")
    pin(c, "league", 850, league_code="nhl", label="Big events")
    cn.reassign_all_channels(c)
    got = numbers(c)
    # nhl sorts before soccer (priority 2 vs unset) → 850, then World Cup 851
    assert (got[7], got[11]) == (850, 851)
    resolver = ne.LaneResolver.load(c, cn._default_lane(c))
    assert len(resolver.lanes()) == 2  # one grouped lane + default


def test_spill_forward_into_next_block():
    c = build(range_start=5000)
    pin(c, "league", 100, league_code="nfl")   # 4 channels: 100-103
    pin(c, "league", 102, league_code="nba")   # would start inside NFL's spill
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert [got[i] for i in (1, 2, 3, 4)] == [100, 101, 102, 103]
    assert (got[5], got[6]) == (104, 105)      # skipped over the spill, no collision


def test_bounded_block_overflows_to_default():
    c = build(range_start=5000)
    pin(c, "league", 100, league_code="nfl", end=101)  # room for 2 of 4
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert (got[1], got[2]) == (100, 101)
    # overflow lands at the tail of the default lane
    default_numbers = sorted(v for k, v in got.items() if k not in (1, 2))
    assert default_numbers[0] == 5000
    assert got[3] > 5000 and got[4] == got[3] + 1


def test_bounded_block_next_channel_overflows_to_default():
    c = build(range_start=5000)
    pin(c, "league", 100, league_code="nfl", end=101)
    c.execute("UPDATE managed_channels SET channel_number = 100 WHERE id = 1")
    c.execute("UPDATE managed_channels SET channel_number = 101 WHERE id = 2")
    assert cn.get_next_channel_number(c, league="nfl", sport="football") == 5000


def test_gap_mode_inside_lane():
    c = build(stab="gap", gap=3, range_start=5000)
    pin(c, "league", 800, league_code="nfl")
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert [got[i] for i in (1, 2, 3, 4)] == [800, 801, 804, 805]  # feeds contiguous, gap between
    assert got[10] == 5000  # default lane starts at its own start


def test_sticky_anchor_outside_its_lane_is_replaced():
    """Moving a block re-places its locked channels on the next run."""
    c = build(stab="gap", gap=3, range_start=5000, locked={1: 800, 2: 801})
    pin(c, "league", 900, league_code="nfl")  # block moved from 800 → 900
    cn.reassign_all_channels(c)
    got = numbers(c)
    assert (got[1], got[2]) == (900, 901)


def test_locked_number_outside_default_lane_is_replaced():
    # nba channel locked at 103 — outside the default lane (5000+) → not an anchor, re-placed.
    c = build(stab="strict", range_start=5000, locked={5: 103})
    cn.reassign_all_channels(c)
    assert numbers(c)[5] >= 5000


def test_disabled_pin_is_ignored():
    c = build()
    exc = pin(c, "team", 800, provider="espn", provider_team_id="8")
    ne.update_numbering_exception(c, exc.id, enabled=False)
    cn.reassign_all_channels(c)
    assert numbers(c)[1] == 101


def test_next_channel_uses_lane():
    c = build()
    pin(c, "team", 800, provider="espn", provider_team_id="8")
    cn.reassign_all_channels(c)
    assert cn.get_next_channel_number(
        c, league="nfl", sport="football", home_team="Detroit Lions", away_team="X"
    ) == 802
    assert cn.get_next_channel_number(c, league="nfl", sport="football") == 110


def test_pin_edits_arm_relayout_in_sticky_mode():
    c = build(stab="gap")
    exc = pin(c, "league", 800, league_code="nfl")
    assert cn._relayout_pending(c)
    cn.clear_channel_relayout(c)
    ne.update_numbering_exception(c, exc.id, start=900)
    assert cn._relayout_pending(c)
    cn.clear_channel_relayout(c)
    ne.delete_numbering_exception(c, exc.id)
    assert cn._relayout_pending(c)


def test_armed_flag_is_ignored_in_compact():
    c = build(stab="compact")
    pin(c, "league", 800, league_code="nfl")
    assert cn._relayout_pending(c)  # armed unconditionally (like sort-priority edits)…
    assert cn.should_run_channel_reset(c) is False  # …but compact never runs a reset


# ---------------------------------------------------------------------------
# 4. CRUD / validation
# ---------------------------------------------------------------------------


def test_add_team_pin_resolves_from_cache_and_rejects_unknown():
    c = build()
    exc = pin(c, "team", 800, provider="espn", provider_team_id="8")
    assert (exc.team_name, exc.sport, exc.scope) == ("Detroit Lions", "football", "team")
    assert ne.add_numbering_exception(c, scope="team", start=800, provider="espn",
                                      provider_team_id="nope") is None


def test_add_league_pin_resolves_sport():
    c = build()
    exc = pin(c, "league", 500, league_code="NFL")
    assert (exc.league_code, exc.sport) == ("nfl", "football")
    assert ne.add_numbering_exception(c, scope="league", start=500, league_code="zzz") is None


@pytest.mark.parametrize("kw", [
    dict(scope="bogus", start=1, sport="football"),
    dict(scope="sport", start=0, sport="football"),
    dict(scope="sport", start=10, end=5, sport="football"),
])
def test_validation_rejects(kw):
    c = build()
    assert ne.add_numbering_exception(c, **kw) is None


def test_update_and_reorder():
    c = build()
    a = pin(c, "league", 500, league_code="nfl")
    b = pin(c, "league", 500, league_code="nba", label="Ball")
    upd = ne.update_numbering_exception(c, a.id, end=520, label="Football")
    assert (upd.end, upd.label) == (520, "Football")
    upd = ne.update_numbering_exception(c, a.id, end=None, label=None)
    assert (upd.end, upd.label) == (None, None)
    assert ne.update_numbering_exception(c, a.id, start=600, end=500) is None  # end < start
    ne.reorder_numbering_exceptions(c, [b.id, a.id])
    assert [e.id for e in ne.get_numbering_exceptions(c)] == [b.id, a.id]


def test_list_order_follows_sort_order_not_start():
    """The reorder arrows must visibly move rows: list order is sort_order, not start."""
    c = build()
    hi = pin(c, "league", 900, league_code="nfl")
    lo = pin(c, "league", 100, league_code="nba")
    assert [e.id for e in ne.get_numbering_exceptions(c)] == [hi.id, lo.id]
    ne.reorder_numbering_exceptions(c, [lo.id, hi.id])
    assert [e.id for e in ne.get_numbering_exceptions(c)] == [lo.id, hi.id]
    # placement order is still by start
    resolver = ne.LaneResolver.load(c, cn._default_lane(c))
    assert [lane.start for lane in resolver.lanes()] == [100, 900, 101]
